"""phase3_candidates_applications_resumes_screening

Revision ID: 4d19caca5613
Revises: None
Create Date: 2026-09-25 18:59:09.484665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d19caca5613'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_code_sequences',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('current_val', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('year'),
    sa.UniqueConstraint('year', name='uq_job_code_sequence_year')
    )
    op.create_table('organizations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('candidates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('candidate_code', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('current_location', sa.String(length=255), nullable=True),
    sa.Column('total_experience', sa.Float(), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('current_company', sa.String(length=255), nullable=True),
    sa.Column('notice_period', sa.String(length=50), nullable=True),
    sa.Column('resume_id', sa.String(length=36), nullable=True),
    sa.Column('first_source', sa.String(length=50), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidates_archived_at'), 'candidates', ['archived_at'], unique=False)
    op.create_index(op.f('ix_candidates_candidate_code'), 'candidates', ['candidate_code'], unique=False)
    op.create_index(op.f('ix_candidates_email'), 'candidates', ['email'], unique=False)
    op.create_index(op.f('ix_candidates_full_name'), 'candidates', ['full_name'], unique=False)
    op.create_index(op.f('ix_candidates_organization_id'), 'candidates', ['organization_id'], unique=False)
    op.create_index(op.f('ix_candidates_phone'), 'candidates', ['phone'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_organization_id'), 'audit_logs', ['organization_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=False),
    sa.Column('updated_by_id', sa.String(length=36), nullable=False),
    sa.Column('job_code', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('employment_type', sa.String(length=50), nullable=True),
    sa.Column('work_mode', sa.String(length=50), nullable=False),
    sa.Column('openings', sa.Integer(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('office_location', sa.String(length=255), nullable=True),
    sa.Column('pin_code', sa.String(length=20), nullable=True),
    sa.Column('allow_relocation', sa.Boolean(), nullable=False),
    sa.Column('min_experience', sa.Float(), nullable=True),
    sa.Column('max_experience', sa.Float(), nullable=True),
    sa.Column('allow_freshers', sa.Boolean(), nullable=False),
    sa.Column('min_qualification', sa.String(length=100), nullable=True),
    sa.Column('degree', sa.String(length=255), nullable=True),
    sa.Column('specialization', sa.String(length=255), nullable=True),
    sa.Column('salary_type', sa.String(length=50), nullable=True),
    sa.Column('min_salary', sa.Float(), nullable=True),
    sa.Column('max_salary', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('show_salary', sa.Boolean(), nullable=False),
    sa.Column('benefits', sa.JSON(), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('responsibilities', sa.JSON(), nullable=False),
    sa.Column('required_qualifications', sa.Text(), nullable=True),
    sa.Column('preferred_qualifications', sa.Text(), nullable=True),
    sa.Column('tech_requirements', sa.Text(), nullable=True),
    sa.Column('soft_skills', sa.Text(), nullable=True),
    sa.Column('certifications', sa.Text(), nullable=True),
    sa.Column('other_requirements', sa.Text(), nullable=True),
    sa.Column('application_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('notice_periods', sa.JSON(), nullable=True),
    sa.Column('languages', sa.JSON(), nullable=True),
    sa.Column('inclusion_info', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('career_page_published', sa.Boolean(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_archived_at'), 'jobs', ['archived_at'], unique=False)
    op.create_index(op.f('ix_jobs_job_code'), 'jobs', ['job_code'], unique=True)
    op.create_index(op.f('ix_jobs_organization_id'), 'jobs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_index(op.f('ix_jobs_title'), 'jobs', ['title'], unique=False)
    op.create_table('resumes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('candidate_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('parsed_data', sa.JSON(), nullable=True),
    sa.Column('parser_version', sa.String(length=20), nullable=False),
    sa.Column('processing_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resumes_candidate_id'), 'resumes', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_resumes_content_hash'), 'resumes', ['content_hash'], unique=False)
    op.create_index(op.f('ix_resumes_organization_id'), 'resumes', ['organization_id'], unique=False)
    op.create_index(op.f('ix_resumes_processing_status'), 'resumes', ['processing_status'], unique=False)
    op.create_table('application_forms',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=False),
    sa.Column('form_version', sa.Integer(), nullable=False),
    sa.Column('source_job_revision', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('questions_schema', sa.JSON(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_form_id', sa.String(length=255), nullable=True),
    sa.Column('respondent_url', sa.String(length=500), nullable=True),
    sa.Column('editor_url', sa.String(length=500), nullable=True),
    sa.Column('creation_status', sa.String(length=50), nullable=False),
    sa.Column('publication_state', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'form_version', name='uq_job_form_version')
    )
    op.create_index(op.f('ix_application_forms_job_id'), 'application_forms', ['job_id'], unique=False)
    op.create_index(op.f('ix_application_forms_organization_id'), 'application_forms', ['organization_id'], unique=False)
    op.create_table('candidate_applications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('candidate_id', sa.String(length=36), nullable=True),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('application_form_id', sa.String(length=36), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('current_location', sa.String(length=255), nullable=True),
    sa.Column('total_experience', sa.Float(), nullable=True),
    sa.Column('current_ctc', sa.String(length=100), nullable=True),
    sa.Column('expected_ctc', sa.String(length=100), nullable=True),
    sa.Column('notice_period', sa.String(length=100), nullable=True),
    sa.Column('resume_url', sa.String(length=500), nullable=True),
    sa.Column('source_channel', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('answers_payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['application_form_id'], ['application_forms.id'], ),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_applications_application_form_id'), 'candidate_applications', ['application_form_id'], unique=False)
    op.create_index(op.f('ix_candidate_applications_candidate_id'), 'candidate_applications', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_candidate_applications_email'), 'candidate_applications', ['email'], unique=False)
    op.create_index(op.f('ix_candidate_applications_job_id'), 'candidate_applications', ['job_id'], unique=False)
    op.create_index(op.f('ix_candidate_applications_organization_id'), 'candidate_applications', ['organization_id'], unique=False)
    op.create_table('job_applications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('candidate_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('job_revision_at_submission', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('resume_id', sa.String(length=36), nullable=True),
    sa.Column('form_id', sa.String(length=36), nullable=True),
    sa.Column('answers_payload', sa.JSON(), nullable=True),
    sa.Column('profile_snapshot', sa.JSON(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['form_id'], ['application_forms.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_applications_candidate_id'), 'job_applications', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_job_applications_idempotency_key'), 'job_applications', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_job_applications_job_id'), 'job_applications', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_applications_status'), 'job_applications', ['status'], unique=False)
    op.create_table('hr_notes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['job_applications.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hr_notes_application_id'), 'hr_notes', ['application_id'], unique=False)
    op.create_table('ingestion_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_application_id', sa.String(length=36), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_application_id'], ['job_applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_events_job_application_id'), 'ingestion_events', ['job_application_id'], unique=False)
    op.create_index(op.f('ix_ingestion_events_status'), 'ingestion_events', ['status'], unique=False)
    op.create_table('screening_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('job_revision', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.String(length=36), nullable=True),
    sa.Column('engine_version', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('recommendation', sa.String(length=50), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('criterion_results', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['job_applications.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_screening_runs_application_id'), 'screening_runs', ['application_id'], unique=False)
    op.create_index(op.f('ix_screening_runs_job_id'), 'screening_runs', ['job_id'], unique=False)
    op.create_table('hr_decisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('decided_by_id', sa.String(length=36), nullable=False),
    sa.Column('decision', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('screening_run_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['job_applications.id'], ),
    sa.ForeignKeyConstraint(['decided_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['screening_run_id'], ['screening_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hr_decisions_application_id'), 'hr_decisions', ['application_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hr_decisions_application_id'), table_name='hr_decisions')
    op.drop_table('hr_decisions')
    op.drop_index(op.f('ix_screening_runs_job_id'), table_name='screening_runs')
    op.drop_index(op.f('ix_screening_runs_application_id'), table_name='screening_runs')
    op.drop_table('screening_runs')
    op.drop_index(op.f('ix_ingestion_events_status'), table_name='ingestion_events')
    op.drop_index(op.f('ix_ingestion_events_job_application_id'), table_name='ingestion_events')
    op.drop_table('ingestion_events')
    op.drop_index(op.f('ix_hr_notes_application_id'), table_name='hr_notes')
    op.drop_table('hr_notes')
    op.drop_index(op.f('ix_job_applications_status'), table_name='job_applications')
    op.drop_index(op.f('ix_job_applications_job_id'), table_name='job_applications')
    op.drop_index(op.f('ix_job_applications_idempotency_key'), table_name='job_applications')
    op.drop_index(op.f('ix_job_applications_candidate_id'), table_name='job_applications')
    op.drop_table('job_applications')
    op.drop_index(op.f('ix_candidate_applications_organization_id'), table_name='candidate_applications')
    op.drop_index(op.f('ix_candidate_applications_job_id'), table_name='candidate_applications')
    op.drop_index(op.f('ix_candidate_applications_email'), table_name='candidate_applications')
    op.drop_index(op.f('ix_candidate_applications_candidate_id'), table_name='candidate_applications')
    op.drop_index(op.f('ix_candidate_applications_application_form_id'), table_name='candidate_applications')
    op.drop_table('candidate_applications')
    op.drop_index(op.f('ix_application_forms_organization_id'), table_name='application_forms')
    op.drop_index(op.f('ix_application_forms_job_id'), table_name='application_forms')
    op.drop_table('application_forms')
    op.drop_index(op.f('ix_resumes_processing_status'), table_name='resumes')
    op.drop_index(op.f('ix_resumes_organization_id'), table_name='resumes')
    op.drop_index(op.f('ix_resumes_content_hash'), table_name='resumes')
    op.drop_index(op.f('ix_resumes_candidate_id'), table_name='resumes')
    op.drop_table('resumes')
    op.drop_index(op.f('ix_jobs_title'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_organization_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_job_code'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_archived_at'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_audit_logs_organization_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_candidates_phone'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_organization_id'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_full_name'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_email'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_candidate_code'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_archived_at'), table_name='candidates')
    op.drop_table('candidates')
    op.drop_table('organizations')
    op.drop_table('job_code_sequences')
    # ### end Alembic commands ###
